// Code generated by hertz generator.

package main

import (
	handler "github.com/Practical-Training-IOT/IOT-C/gateway/biz/handler"
	"github.com/Practical-Training-IOT/IOT-C/gateway/biz/router"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	router.SetAlarmRouter(r)
	router.SetUserRouter(r)
	router.SetSceneRouter(r)
	router.SetAIRouter(r)
	// your code ...
}
