// Code generated by Kitex v0.13.1. DO NOT EDIT.

package user

import (
	"context"
	"errors"
	user "github.com/Practical-Training-IOT/IOT-C/kitex_gen/iot/user"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserRegisterArgs,
		newUserRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserLoginArgs,
		newUserLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UserInfo": kitex.NewMethodInfo(
		userInfoHandler,
		newUserUserInfoArgs,
		newUserUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UserInfoUpload": kitex.NewMethodInfo(
		userInfoUploadHandler,
		newUserUserInfoUploadArgs,
		newUserUserInfoUploadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceInfo                = NewServiceInfo()
	userServiceInfoForClient       = NewServiceInfoForClient()
	userServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "user"
	handlerType := (*user.User)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserRegisterArgs)
	realResult := result.(*user.UserRegisterResult)
	success, err := handler.(user.User).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserRegisterArgs() interface{} {
	return user.NewUserRegisterArgs()
}

func newUserRegisterResult() interface{} {
	return user.NewUserRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserLoginArgs)
	realResult := result.(*user.UserLoginResult)
	success, err := handler.(user.User).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserLoginArgs() interface{} {
	return user.NewUserLoginArgs()
}

func newUserLoginResult() interface{} {
	return user.NewUserLoginResult()
}

func userInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserUserInfoArgs)
	realResult := result.(*user.UserUserInfoResult)
	success, err := handler.(user.User).UserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserUserInfoArgs() interface{} {
	return user.NewUserUserInfoArgs()
}

func newUserUserInfoResult() interface{} {
	return user.NewUserUserInfoResult()
}

func userInfoUploadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserUserInfoUploadArgs)
	realResult := result.(*user.UserUserInfoUploadResult)
	success, err := handler.(user.User).UserInfoUpload(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserUserInfoUploadArgs() interface{} {
	return user.NewUserUserInfoUploadArgs()
}

func newUserUserInfoUploadResult() interface{} {
	return user.NewUserUserInfoUploadResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *user.RegisterReq) (r *user.RegisterRes, err error) {
	var _args user.UserRegisterArgs
	_args.Req = req
	var _result user.UserRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *user.LoginReq) (r *user.LoginRes, err error) {
	var _args user.UserLoginArgs
	_args.Req = req
	var _result user.UserLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserInfo(ctx context.Context, req *user.UserInfoReq) (r *user.UserInfoRes, err error) {
	var _args user.UserUserInfoArgs
	_args.Req = req
	var _result user.UserUserInfoResult
	if err = p.c.Call(ctx, "UserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserInfoUpload(ctx context.Context, req *user.UserInfoUploadReq) (r *user.UserInfoUploadRes, err error) {
	var _args user.UserUserInfoUploadArgs
	_args.Req = req
	var _result user.UserUserInfoUploadResult
	if err = p.c.Call(ctx, "UserInfoUpload", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
