// Code generated by Kitex v0.13.1. DO NOT EDIT.

package ai

import (
	"context"
	ai "github.com/Practical-Training-IOT/IOT-C/kitex_gen/iot/ai"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	OneHistory(ctx context.Context, req *ai.OneHistoryRequest, callOptions ...callopt.Option) (r *ai.OneHistoryResponse, err error)
	Chat(ctx context.Context, req *ai.ChatRequest, callOptions ...callopt.Option) (r *ai.ChatResponse, err error)
	Change(ctx context.Context, req *ai.ChangeRequest, callOptions ...callopt.Option) (r *ai.ChangeResponse, err error)
	History(ctx context.Context, req *ai.HistoryRequest, callOptions ...callopt.Option) (r *ai.HistoryResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAiClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAiClient struct {
	*kClient
}

func (p *kAiClient) OneHistory(ctx context.Context, req *ai.OneHistoryRequest, callOptions ...callopt.Option) (r *ai.OneHistoryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.OneHistory(ctx, req)
}

func (p *kAiClient) Chat(ctx context.Context, req *ai.ChatRequest, callOptions ...callopt.Option) (r *ai.ChatResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Chat(ctx, req)
}

func (p *kAiClient) Change(ctx context.Context, req *ai.ChangeRequest, callOptions ...callopt.Option) (r *ai.ChangeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Change(ctx, req)
}

func (p *kAiClient) History(ctx context.Context, req *ai.HistoryRequest, callOptions ...callopt.Option) (r *ai.HistoryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.History(ctx, req)
}
