// Code generated by Kitex v0.13.1. DO NOT EDIT.

package alarm

import (
	"context"
	alarm "github.com/Practical-Training-IOT/IOT-C/kitex_gen/iot/alarm"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AlarmList(ctx context.Context, req *alarm.AlarmListReq, callOptions ...callopt.Option) (r *alarm.AlarmListResp, err error)
	AlarmDetail(ctx context.Context, req *alarm.AlarmDetailReq, callOptions ...callopt.Option) (r *alarm.AlarmDetailResp, err error)
	AlarmSearch(ctx context.Context, req *alarm.AlarmSearchReq, callOptions ...callopt.Option) (r *alarm.AlarmSearchResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAlarmClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAlarmClient struct {
	*kClient
}

func (p *kAlarmClient) AlarmList(ctx context.Context, req *alarm.AlarmListReq, callOptions ...callopt.Option) (r *alarm.AlarmListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AlarmList(ctx, req)
}

func (p *kAlarmClient) AlarmDetail(ctx context.Context, req *alarm.AlarmDetailReq, callOptions ...callopt.Option) (r *alarm.AlarmDetailResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AlarmDetail(ctx, req)
}

func (p *kAlarmClient) AlarmSearch(ctx context.Context, req *alarm.AlarmSearchReq, callOptions ...callopt.Option) (r *alarm.AlarmSearchResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AlarmSearch(ctx, req)
}
