// Code generated by Kitex v0.13.1. DO NOT EDIT.

package scene

import (
	"context"
	scene "github.com/Practical-Training-IOT/IOT-C/kitex_gen/iot/scene"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	List(ctx context.Context, req *scene.SceneListReq, callOptions ...callopt.Option) (r *scene.SceneListRes, err error)
	UpdateEnable(ctx context.Context, req *scene.SceneUpdateEnableReq, callOptions ...callopt.Option) (r *scene.SceneUpdateEnableRes, err error)
	Detail(ctx context.Context, req *scene.SceneDetailReq, callOptions ...callopt.Option) (r *scene.SceneDetailRes, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kSceneClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSceneClient struct {
	*kClient
}

func (p *kSceneClient) List(ctx context.Context, req *scene.SceneListReq, callOptions ...callopt.Option) (r *scene.SceneListRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.List(ctx, req)
}

func (p *kSceneClient) UpdateEnable(ctx context.Context, req *scene.SceneUpdateEnableReq, callOptions ...callopt.Option) (r *scene.SceneUpdateEnableRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateEnable(ctx, req)
}

func (p *kSceneClient) Detail(ctx context.Context, req *scene.SceneDetailReq, callOptions ...callopt.Option) (r *scene.SceneDetailRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Detail(ctx, req)
}
